### ISSUE TITLE
SoundCloud profile?

### ISSUE THREAD

**Issue by timmkrause** [timoknapp/sound-on-fire#41]
I assume SoundCloud APIs do not allow logging in by 3rd party apps and/or list playlists by specific profiles, right?

I'm searching for an alternative on Fire TV that allows navigating playlists, likes etc. from my profile, to have a convenient way to access my music.

I do not want to copy paste or type and search stuff, as it feels unproductive.

**Comment by timoknapp** [comment]
Hi @timmkrause,

in order to provide a login feature, it is required to become a registered SoundCloud App. SoundCloud closed their developer program quite a while ago already. Whenever they open up again, I am planning to extend the current feature set accordingly. 

The current feature set of SoundOnFire simply does the same as you can do with your web browser, when not being logged in.

In case you find another convenient way of achieving your pursued features, I am happy for PRs! :)

Regards
Timo

**Comment by timoknapp** [comment]
Lets close this issue for now. I will keep you posted whenever there will be a login feature 😉
